### ISSUE TITLE
Remove (legacy) function get_plugin_path from countdown-util.php

### ISSUE THREAD

**Issue by ElpyDE** [shailancom/wordpress-countdown-widget#15]
Got a deprecation warning on my site for deprecated use of `get_bloginfo('siteurl')` that originated from this function.

After a closer look, it turned out this function is only used once here: https://github.com/shailancom/wordpress-countdown-widget/blob/master/countdown-widget.php#L110

```php
$path = get_plugin_path(__FILE__);
```

The variable `$path` is then never used. Instead, I found several uses of the WP builtin functions `plugin_dir_path()` and `plugins_url()` that seem to do the job (now).

Cleanup appreciated 😉 

Edit: Backwards compatibility should not be an issue. The above mentioned builtin functions were introduced in WP versions 2.8.0 and 2.6.0, respectively. And after all, the result is never used.

**Comment by metinsaylan** [comment]
Thanks a lot for feedback. I will remove it ASAP. Best.

**Comment by metinsaylan** [comment]
This issue is fixed in release 2.6.4 fix 1
