### ISSUE TITLE
Vertically aligning text

### ISSUE THREAD

**Issue by shivors** [shailancom/wordpress-countdown-widget#3]
Added background, adjusted height and need to vertically align text. Everything I have tried has not worked. 

![capture](https://cloud.githubusercontent.com/assets/18252748/14236281/7251f73a-f9d8-11e5-80af-2b3f9bd18006.PNG)

**Comment by metinsaylan** [comment]
This can be done via padding. 
Please use some top padding for .countdown:

    .countdown {
        padding: 30px 10px;
    }
