### ISSUE TITLE
Question: Is there a way for individual accounts to be able to fill out a form for the countdown to then appear via shortcode

### ISSUE THREAD

**Issue by cartermadeit** [shailancom/wordpress-countdown-widget#4]
I was inquiring to whether or not there is a way for an individual user on a site like a "subscriber" to be able to fill out a form that will then allow the user to set their individual countdown clock based on the form?

**Comment by metinsaylan** [comment]
If your users have access to edit post screen, they can use shortcode to add countdowns. If they don't have access, maybe you need a plugin to [allow guest post](https://premium.wpmudev.org/blog/wordpress-post-frontend-plugins/).
