### ISSUE TITLE
Can I use two digits in countdown_section

### ISSUE THREAD

**Issue by Tusca95** [shailancom/wordpress-countdown-widget#5]
I need to show two 0 when it goes to 0 in a countdown_section because i gave to the css a border radius and i need to have all circles even if the countdown_section reach the end of the count. So it would be nice if 9, 8, 7, 6, 5, 4, 3, 2, 1 numbers has the 0.

Thank you in advance!

**Comment by metinsaylan** [comment]
You can set a fixed width for elements so they will always appear same width using CSS:

```
display: inline-block;
height: 36px;
width: 36px;
```
