### ISSUE TITLE
Call to undefined function wp_doing_ajax() countdown-widget.php on line 317

### ISSUE THREAD

**Issue by bossgos** [shailancom/wordpress-countdown-widget#6]
Hello,
after installation my site stop working and I have error:

Fatal error: Call to undefined function wp_doing_ajax() in /wp-content/plugins/wordpress-countdown-widget/countdown-widget.php on line 317
Wordpress 4.6.3

What can I do?

**Comment by metinsaylan** [comment]
Hello @bossgos this is caused because of a function added in WP 4.7 was used. I will fix it in the next version for backwards compatibility. Thanks for reporting.
